---

# Required packages:
#   unzip
#   unrar
#

# Required variables or facts:
#   _sapBom
#   _installDirPath
#


# *====================================4=======================================8
#
#                              BOM Registration
#
# *====================================4=======================================8
#
#   Purpose:
#     Reads in the BOM file and makes the included variables and dictionaries
#     available under the sapbom object ID.
#
#   Available objects:
#     sapbom.productIdSCS
#     sapbom.productIdHDB
#     sapbom.productIdPAS
#     sapbom.productIdAPP
#     sapbom.productIdWEB
#     sapbom.sasToken
#     sapbom.billOfMaterials
#     sapbom.billOfMaterials.url
#     sapbom.billOfMaterials.fileName
#     sapbom.billOfMaterials.permissions
#     sapbom.billOfMaterials.extract
#     sapbom.billOfMaterials.extractDir
#     sapbom.billOfMaterials.creates
#     sapbom.billOfMaterials.download
#     sapbom.billOfMaterials.sourceUrl
#
- name:         "BOM: Register BOM"
  include_vars:
    file:       "../../sap-bom-files/files/BOM_{{ _sapBom }}.yaml"
    name:       sapbom

- name:         "BOM: Register Database BOM"
  include_vars:
    file:       "../../sap-bom-files/files/BOM_{{ sapbom.databaseBom }}.yaml"
    name:       sapdbbom

# *=========== DEBUGGING ==============4
# - debug:  
#     msg:      "URL: {{ item.url }}"
#   loop:       "{{ sapbom.billOfMaterials|flatten(levels=1) }}"
#
# - debug:  
#     msg:      "URL: {{ item.url }}"
#   loop:       "{{ sapdbbom.billOfMaterials|flatten(levels=1) }}"
#
# - debug:  
#     msg:      "URL: {{ item.url }}"
# #  loop:       "{{ (sapbom.billOfMaterials|flatten(levels=1)) + (sapdbbom.billOfMaterials|flatten(levels=1)) }}"
#   loop:       "{{        (   sapbom.billOfMaterials | flatten(levels=1) )
#                   | union( sapdbbom.billOfMaterials | flatten(levels=1) ) }}"
# *================2===================4


# *====================================4=======================================8
#
#                           Create Install Directories
#
# *====================================4=======================================8
#
#   Purpose:
#     Create the Install directory structure.
#
- name:         "BOM: Create SAP download directories"
  file:
    path:       "{{ _installDirPath }}/{{ item.dir }}"
    state:      directory
    mode:       0755
  loop:
    - { dir: 'downloads' }
    - { dir: 'download_basket' }


# *====================================4=======================================8
#
#                           Create Extract Directories
#
# *====================================4=======================================8
#
#   Purpose:
#     Create the directory structure into which software will be extracted.
#
- name:         "BOM: Create BOM extraction directories"
  file:
    path:       "{{ _installDirPath }}/{{ item.extractDir }}"
    state:      directory
    mode:       0755
  loop:         "{{        (   sapbom.billOfMaterials | flatten(levels=1) )
                    | union( sapdbbom.billOfMaterials | flatten(levels=1) ) }}"
  when:         not (    (item.extractDir is undefined)
                      or (item.extractDir == '') )


# *====================================4=======================================8
#
#                              Download Software
#
# *====================================4=======================================8
#
#   Purpose:
#     Download the software from the customer storage account
#
- name:         "BOM: Download Files"
  get_url:
    url:        "{{ item.url }}{% if sapbom.sasToken is not undefined %}{{ sapbom.sasToken }}{% endif %}"
    dest:       "{{ _installDirPath }}/{{ item.fileName }}"
    mode:       "{% if item.permissions is undefined %}0644{% else %}{{ item.permissions }}{% endif %}"

  register:     result
  until:        result is succeeded
  retries:      10
  delay:        5
  loop:         "{{        (   sapbom.billOfMaterials | flatten(levels=1) )
                    | union( sapdbbom.billOfMaterials | flatten(levels=1) ) }}"
  when:         item.download is undefined or
                item.download


# *====================================4=======================================8
#
#                               File Extractors
#
# *====================================4=======================================8
#
#   Purpose:
#     Use SAPCAR to perform required extractions
#
- name:         "BOM: Extract File, SAPCAR"
  command:      "{{ _installDirPath }}/downloads/SAPCAR -manifest SIGNATURE.SMF -xf '{{ _installDirPath }}/{{ item.fileName }}'"
  args:
    chdir:      "{{ _installDirPath }}/{{ item.extractDir }}"
    creates:    "{{ _installDirPath }}/{{ item.extractDir }}/{{ item.creates }}"
  loop:         "{{        (   sapbom.billOfMaterials | flatten(levels=1) )
                    | union( sapdbbom.billOfMaterials | flatten(levels=1) ) }}"
  when:         not (    (item.extractDir is undefined)
                      or (item.extractDir == '') )
                and (item.fileName|regex_search('[^.]+(?=\\.*$)')|upper=="SAR")

#
#   Purpose:
#     Use UNRAR to perform required extractions
#
- name:         "BOM: Extract File, UNRAR"
  command:      unrar x "{{ _installDirPath }}/{{ item.fileName }}"
  args:
    chdir:      "{{ _installDirPath }}/{{ item.extractDir }}"
    creates:    "{{ _installDirPath }}/{{ item.extractDir }}/{{ item.creates }}"
  loop:         "{{        (   sapbom.billOfMaterials | flatten(levels=1) )
                    | union( sapdbbom.billOfMaterials | flatten(levels=1) ) }}"
  when:         not (    (item.extractDir is undefined)
                      or (item.extractDir == '') )
                and (item.fileName|regex_search('[^.]+(?=\\.*$)')|upper=="RAR")


#
#   Purpose:
#     Use UNZIP to perform required extractions
#
- name:         "BOM: Extract File, UNZIP"
  unarchive:
    src:        "{{ _installDirPath }}/{{ item.fileName }}"
    dest:       "{{ _installDirPath }}/{{ item.extractDir }}"
    remote_src: yes
    creates:    "{{ _installDirPath }}/{{ item.extractDir }}/{{ item.creates }}"
  loop:         "{{        (   sapbom.billOfMaterials | flatten(levels=1) )
                    | union( sapdbbom.billOfMaterials | flatten(levels=1) ) }}"
  when:         not (    (item.extractDir is undefined)
                      or (item.extractDir == '') )
                and (item.fileName|regex_search('[^.]+(?=\\.*$)')|upper=="ZIP")

...