# /*----------------------------------------------------------------------------8
# |                                                                             |
# |                      Playbook for SAP DB Load                               |
# |                                                                             |
# +-------------------------------------4--------------------------------------*/
---









...
# /*----------------------------------------------------------------------------8
# |                                    END                                      |
# +-------------------------------------4--------------------------------------*/
