---

- hosts: scs
  become: yes
  vars:
    tier: preparation
  vars_files:
    - "{{ inventory_dir }}/sap_system_configuration.yml"
  roles:
    - role: disk-setup
    - role: swap-setup
    - role: ensure-bom
    - role: process_bom
    - role: nfs-server-setup
