# /*----------------------------------------------------------------------------8
# |                                                                             |
# |         Playbook for performing SAP specific OS configuration tasks         |
# |                                                                             |
# +-------------------------------------4--------------------------------------*/
---

- hosts:        "{{ app_sid|upper }}_DB  :
                 {{ app_sid|upper }}_SCS :
                 {{ app_sid|upper }}_PAS :
                 {{ app_sid|upper }}_APP :
                 {{ app_sid|upper }}_WEB"
  name:         SAP specific OS configuration
  remote_user:  azureadm                              # TODO: Replace with variable
  become:       yes
  become_user:  root


  tasks:

  - name: Test Connection                             # TODO: Temp place holder
    ping:







...
# /*----------------------------------------------------------------------------8
# |                                    END                                      |
# +-------------------------------------4--------------------------------------*/
