# /*----------------------------------------------------------------------------8
# |                                                                             |
# |         Playbook for performing SAP specific OS configuration tasks         |
# |                                                                             |
# +-------------------------------------4--------------------------------------*/
---

# - hosts:        scs                                   # TODO: Replace this with new inventory group; Change to correct group
- hosts:        "all.{{ app_sid|upper }}.DB  :
                 {{ app_sid|upper }}.SCS :
                 {{ app_sid|upper }}.PAS :
                 {{ app_sid|upper }}.APP :
                 {{ app_sid|upper }}.WEB"
  name:         SAP specific OS configuration
  remote_user:  azureadm                              # TODO: Replace with variable
  become:       yes
  become_user:  root


  tasks:

  - name: Test Connection                             # TODO: Temp place holder
    ping:







...
# /*----------------------------------------------------------------------------8
# |                                    END                                      |
# +-------------------------------------4--------------------------------------*/
