# /*----------------------------------------------------------------------------8
# |                                                                             |
# |                      Playbook for SAP DB Load                               |
# |                                                                             |
# +-------------------------------------4--------------------------------------*/
---

- hosts:        "{{ app_sid|upper }}_PAS"
  name:         SAP Installation - DB Load
  remote_user:  azureadm                              # TODO: Replace with variable
  become:       yes
  become_user:  root
  vars_files:
    - vars/ansible-input-api.yaml                     # DONE: move this back into Repo Structure as an API template


  tasks:

  - name: Test Connection                             # TODO: Temp place holder
    ping:








...
# /*----------------------------------------------------------------------------8
# |                                    END                                      |
# +-------------------------------------4--------------------------------------*/
