# /*----------------------------------------------------------------------------8
# |                                                                             |
# |                   Playbook for SAP Web Dispatcher Install                   |
# |                                                                             |
# +-------------------------------------4--------------------------------------*/
---

- hosts:        "{{ sap_sid|upper }}_WEB"
  name:         SAP Installation - WEB
  remote_user:  azureadm                              # TODO: Replace with variable
  become:       yes
  become_user:  root
  vars_files:
    - vars/ansible-input-api.yaml                     # DONE: move this back into Repo Structure as an API template


  tasks:

  - name: Test Connection                             # TODO: Temp place holder
    ping:








...
# /*----------------------------------------------------------------------------8
# |                                    END                                      |
# +-------------------------------------4--------------------------------------*/
