# /*----------------------------------------------------------------------------8
# |                                                                             |
# |       Playbook for performing general baseline OS configuration tasks       |
# |                                                                             |
# +-------------------------------------4--------------------------------------*/
---









...
# /*----------------------------------------------------------------------------8
# |                                    END                                      |
# +-------------------------------------4--------------------------------------*/
