# /*----------------------------------------------------------------------------8
# |                                                                             |
# |         Playbook for performing SAP specific OS configuration tasks         |
# |                                                                             |
# +-------------------------------------4--------------------------------------*/
---

- hosts:        "{{ sap_sid|upper }}_DB  :
                 {{ sap_sid|upper }}_SCS :
                 {{ sap_sid|upper }}_PAS :
                 {{ sap_sid|upper }}_APP :
                 {{ sap_sid|upper }}_WEB"
  name:         SAP specific OS configuration
  remote_user:  azureadm                                        # TODO: Replace with variable
  become:       yes
  become_user:  root
  vars_files:
    - vars/ansible-input-api.yaml                               # DONE: move this back into Repo Structure as an API template


  tasks:

  # - name: Test Connection                                     # TODO: Temp place holder
  #   ping:

# - role: dependencies-install                                  # --> roles-sap/sap-packages (playbook_02_os_sap_specific_config)
  - include_role:
      name:     roles-sap-os/sap-packages                       # TODO: Centiq copy (rework done)


  - include_role:
      name:     roles-sap-os/sap-disk-setup                     # TODO: Centiq copy (rework done)


# - role: sap-users                                             # --> roles-sap/sap-users (playbook_02_os_sap_specific_config)
  - include_role:
      name:     roles-sap-os/sap-users                          # TODO: Centiq copy (rework done)








...
# /*----------------------------------------------------------------------------8
# |                                    END                                      |
# +-------------------------------------4--------------------------------------*/
