# /*----------------------------------------------------------------------------8
# |                                                                             |
# |                         PLAYBOOK FOR BOM PROCESSING                         |
# |                                                                             |
# +-------------------------------------4--------------------------------------*/
---

- hosts:        scs                                   # TODO: Replace this with new inventory group
  name:         BOM Processing
  remote_user:  azureadm                              # TODO: Replace with variable
  become:       yes
  become_user:  root
  gather_facts: true
  vars_files:
    - vars/ansible-input-api.yaml                     # DONE: move this back into Repo Structure as an API template


#---------------------------
#  BEGIN: Centiq
#---------------------------

# - hosts: scs
#   become: yes
  vars:
    tier: preparation
  # vars_files:
  #   - "{{ inventory_dir }}/sap-system-config.yml"
  roles:
    - role: dependencies-install
    - role: disk-setup
    - role: swap-setup
    # - role: ensure-bom                              # --> roles-sap/bom-fetch
    # - role: process_bom                             # --> roles-sap/bom-processing
    # - role: nfs-server-setup                        # --> roles-sap-os/nfs-server-setup

#---------------------------
#  END  : Centiq
#---------------------------


  tasks:

  - set_fact:
      tier:     preparation

  - include_role:
      name:     roles-sap/bom-fetch                             # TODO: Centiq copy (rework needed)

  - include_role:
      name:     roles-sap/bom-processing                        # TODO: Centiq copy (rework needed)

  - include_role:
      name:     roles-sap-os/sap-users                          # TODO: Centiq copy (rework done)

  - include_role:
      name:     roles-sap-os/nfs-server-setup                   # TODO: Centiq copy (rework needed)




#---------------------------
#  BEGIN: EXAMPLE
#---------------------------

# - hosts:        "{{ sapSid|lower }}scs00"
#   name:         test
#   remote_user:  ansible
#   become:       yes
#   become_user:  root
#   gather_facts: true
#   vars_files:
#     - vars/default.yaml


#   tasks:

#   - set_fact:
#       tier:     preparation

#   - include_role:
#       name: roles-sap/sapLvmSetup

#   - include_role:
#       name: roles-sap/sapMounts

#   - include_role:
#       name: roles-sap/sapPackages

#   - include_role:
#       name: roles-sap/sapExports

#   - include_role:
#       name: roles-sap/sapBom

#---------------------------
#  END  : EXAMPLE
#---------------------------


...
# /*----------------------------------------------------------------------------8
# |                                    END                                      |
# +-------------------------------------4--------------------------------------*/
