---

- name: Check if swapfile exists
  stat:
    path: /mnt/swapfile
    get_checksum: false
  register: chk_swapfile

- name: Ensure Resource disk is formatted
  lineinfile:
    state: present
    dest: /etc/waagent.conf
    regexp: 'ResourceDisk.Format='
    line: 'ResourceDisk.Format=y'
  when: not chk_swapfile.stat.exists

- name: Ensure swap is enabled
  lineinfile:
    state: present
    dest: /etc/waagent.conf
    regexp: 'ResourceDisk.EnableSwap='
    line: 'ResourceDisk.EnableSwap=y'
  when: not chk_swapfile.stat.exists

- name: Ensure swapfile size
  lineinfile:
    state: present
    dest: /etc/waagent.conf
    regexp: 'ResourceDisk.SwapSizeMB='
    line: 'ResourceDisk.SwapSizeMB={{ item.swap_size_mb }}'
  when: not chk_swapfile.stat.exists

- name: Ensure waagent is restarted
  service:
    name: waagent
    state: restarted
