---

- name: Check if swapfile exists
  stat:
    path: "{{ item.swap_file }}"
    get_checksum: false
  register: chk_swapfile

- name: Ensure swapfile exists
  command: "dd if=/dev/zero of={{ item.swap_file }} bs=1M count={{ item.swap_size_mb }}"
  when: not chk_swapfile.stat.exists

- name: Ensure the swapfile is useable as a swap
  command: "mkswap {{ item.swap_file }}"
  when: not chk_swapfile.stat.exists

- name: Ensure the swapfile is in /etc/fstab
  when: not chk_swapfile.stat.exists
  lineinfile:
    regexp: "^{{ item.swap_file }}"
    path: /etc/fstab
    line: "{{ item.swap_file }} none swap sw 0 0"
    state: present

- name: Ensure swap is enabled
  command: "swapon -a"

- name: Ensure swappiness is configured
  sysctl:
    name: vm.swappiness
    value: "1"
